### PR TITLE
[NG-3507] Upgrade Dependencies

### PR DESCRIPTION
**Pull request by limtingzhi**
**Changes:**
- Upgrade dependencies (minor and `semantic-release` dependency)
- Remove unused `flow` dependency
- Fix vulnerabilities
- Update GitHub Actions

**JIRA Tickets:**
- [Actions PR Changelog] Upgrade Dependencies (Dec 2022) (https://nugitco.atlassian.net/browse/NG-3507)

### CODE REVIEW

**Review by moroine — APPROVED** [review]
What about upgrading the runtime to NodeJs 16 as nodeJs12 is deprecated https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16

**Comment by limtingzhi** [comment]
> What about upgrading the runtime to NodeJs 16 as nodeJs12 is deprecated https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16

@moroine I have updated to node 16.

**Review by moroine — CHANGES_REQUESTED** [review]
You need to update https://github.com/nugit/actions-pr-changelog/blob/fix/dependencies/action.yml#L15 & https://github.com/nugit/actions-pr-changelog/blob/fix/dependencies/createReleaseAction/action.yml#L20 too

**Review by moroine — APPROVED** [review]

**Pull request merged**
